recipe_database = ["http://www.foodnetwork.com/recipes/emeril-lagasse/vegetarian-chili-recipe.html"  , 
 "http://www.foodnetwork.com/recipes/giada-de-laurentiis/grilled-vegetables-recipe.html"  ,  
 "http://www.foodnetwork.com/recipes/alton-brown/garden-vegetable-soup-recipe.html" ,
  "http://www.foodnetwork.com/recipes/giada-de-laurentiis/frittata-with-asparagus-tomato-and-fontina-recipe.html" , 
  "http://www.foodnetwork.com/recipes/bobby-flay/buckwheat-noodle-salad-recipe.html" ,
   "http://www.foodnetwork.com/recipes/food-network-kitchens/tofu-tacos-recipe.html" , 
   "http://www.foodnetwork.com/recipes/robin-miller/vegetarian-paella-recipe.html" , 
    "http://www.foodnetwork.com/recipes/alton-brown/vegetarian-steamed-dumplings-recipe.html" , 
     "http://www.foodnetwork.com/recipes/vegetarian-southern-style-collard-greens-recipe.html" , 
     "http://www.foodnetwork.com/recipes/food-network-kitchens/vegetable-biryani-recipe.html" , 
      "http://www.foodnetwork.com/recipes/food-network-kitchens/roasted-root-vegetables-recipe.html" , 
      "http://www.foodnetwork.com/recipes/ellie-krieger/grilled-vegetable-salad-with-feta-and-mint-recipe.html" , 
      "http://www.foodnetwork.com/recipes/alton-brown/vegetable-curry-recipe.html" , 
       "http://www.foodnetwork.com/recipes/rachael-ray/three-vegetable-penne-with-tarragon-basil-pesto-recipe.html" , 
       "http://www.foodnetwork.com/recipes/food-network-kitchens/vegetarian-ribollita-recipe.html" , 
        "http://www.foodnetwork.com/recipes/rachael-ray/roasted-squash-vegetable-medley-recipe.html" , 
        "http://www.foodnetwork.com/recipes/food-network-kitchens/seven-vegetable-couscous-recipe.html" , 
        "http://www.foodnetwork.com/recipes/moroccan-vegetables-with-couscous-recipe.html" ,
         "http://www.foodnetwork.com/recipes/vegetable-lasagna.html" ,
          "http://www.foodnetwork.com/recipes/vegetable-tofu-stir-fry-recipe.html" , 
          "http://www.foodnetwork.com/recipes/emeril-lagasse/creole-vegetable-jambalaya-recipe.html", 
          "http://www.foodnetwork.com/recipes/food-network-kitchens/shrimp-and-kale-pitas.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/skillet-orzo-with-tuna.html",
          "http://www.foodnetwork.com/recipes/rachael-ray/parmesan-crusted-chicken-breasts-with-tomato-and-basil-and-potatoes-with-peppers-and-onions-recipe.html",
          "http://www.foodnetwork.com/recipes/tyler-florence/chicken-stir-fry-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/gnocchi-with-bacon-and-escarole.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/turkey-sausage-tacos.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/glazed-salmon-with-spiced-carrots-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/white-clam-pizza-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/almost-famous-chicken-lettuce-wraps-recipe.html",
          "http://www.foodnetwork.com/recipes/guy-fieri/kobe-sliders-recipe.html",
          "http://www.foodnetwork.com/recipes/rachael-ray/buffalo-chicken-salad-recipe.html",
          "http://www.foodnetwork.com/recipes/guy-fieri/grilled-chicken-tortilla-soup-with-tequila-crema-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/chinese-beef-with-broccoli-recipe.html",
          "http://www.foodnetwork.com/recipes/guy-fieri/chicken-avocado-egg-rolls-recipe.html",
          "http://www.foodnetwork.com/recipes/tyler-florence/chicken-parmesan-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/general-tsos-chicken-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/spanish-style-noodles-with-chicken-and-sausage-recipe.html",
          "http://www.foodnetwork.com/recipes/rachael-ray/sausage-kale-and-lentil-soup-recipe.html",
          "http://www.foodnetwork.com/recipes/tyler-florence/beef-stroganoff-with-buttered-noodles-recipe.html",
          "http://www.foodnetwork.com/recipes/giada-de-laurentiis/chicken-carbonara-recipe.html",
          "http://www.foodnetwork.com/recipes/ree-drummond/pan-fried-pork-chops-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/beef-stroganoff-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/spaghetti-carbonara-recipe.html",
          "http://www.foodnetwork.com/recipes/ree-drummond/chicken-fried-steak-with-gravy-recipe.html",
          "http://www.foodnetwork.com/recipes/bobby-flay/shrimp-and-grits-recipe.html","http://www.foodnetwork.com/recipes/food-network-kitchens/patty-melts-recipe.html","http://www.foodnetwork.com/recipes/claire-robinson/beef-stroganoff-recipe.html","http://www.foodnetwork.com/recipes/amy-thielen/peppered-pork-and-parmesan-flatbread-sandwiches.html","http://www.foodnetwork.com/recipes/amy-thielen/oven-baked-short-ribs-with-porter-beer-mop.html","http://www.foodnetwork.com/recipes/amy-thielen/roast-chicken-with-green-herb-stuffing.html"]