recipe_database = ["http://www.foodnetwork.com/recipes/emeril-lagasse/vegetarian-chili-recipe.html", 
"http://www.foodnetwork.com/recipes/paula-deen/broccoli-salad-recipe.html",
"http://www.foodnetwork.com/recipes/trisha-yearwood/strawberry-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ellie-krieger/cucumber-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/shrimp-salad-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/mediterranean-salad-recipe.html",
"http://www.foodnetwork.com/recipes/guy-fieri/jicama-slaw-recipe.html",
"http://www.foodnetwork.com/recipes/paula-deen/southern-cornbread-salad-recipe.html",
"http://www.foodnetwork.com/recipes/emeril-lagasse/rock-shrimp-quesadillas-with-cantaloupe-berry-and-peach-salsa-recipe.html",
"http://www.foodnetwork.com/recipes/jicama-salad-recipe0.html",
"http://www.foodnetwork.com/recipes/chicken-paillard-with-tri-olive-tapanade-roast-sage-yams-and-sauteed-garlic-spinach-recipe.html",
"http://www.foodnetwork.com/recipes/lima-bean-soup-with-parmesan-bacon-crisp-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/broccoli-with-garlic-and-soy-sauce-recipe3.html",
"http://www.foodnetwork.com/recipes/cantaloupe-salad-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/gazpacho-with-lime-chicken-recipe.html",
"http://www.foodnetwork.com/recipes/rachael-ray/cuban-spiced-pork-tenderloin-and-soffrito-rice-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/kiwi-watermelon-lime-juice.html",
"http://www.foodnetwork.com/recipes/kiwi-and-mango-tartlets-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/salami-bacon-and-spinach-hash-recipe.html",
"http://www.foodnetwork.com/recipes/ellie-krieger/radiance-fruit-salad-recipe.html",
"http://www.foodnetwork.com/recipes/sunny-anderson/smoked-gouda-chorizo-jalapeno-poppers-recipe.html",
"http://www.foodnetwork.com/recipes/jalapeno-poppers-three-ways-recipe.html",
"http://www.foodnetwork.com/recipes/melissa-darabian/sweet-potato-beet-hash-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/roasted-beets-with-lemon-recipe.html",
"http://www.foodnetwork.com/recipes/anne-burrell/roasted-beet-salad-with-pears-and-marcona-almonds-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/beet-and-goat-cheese-arugula-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/date-nut-spice-bread-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/beet-and-marinated-goat-cheese-salad-recipe.html",
"http://www.foodnetwork.com/recipes/stilton-stuffed-dates-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/apple-and-mint-punch-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/strawberry-green-tea-smoothie.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/roasted-beets-with-feta-recipe.html",
"http://www.foodnetwork.com/recipes/sticky-toffee-date-cake-recipe.html",
"http://www.foodnetwork.com/recipes/dave-lieberman/mint-iced-tea-recipe.html",
"http://www.foodnetwork.com/recipes/sandra-lee/iced-ginger-green-tea-recipe.html",
"http://www.foodnetwork.com/recipes/dave-lieberman/ricotta-stuffed-bacon-wrapped-dates-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/walnut-and-blue-cheese-grapes-recipe.html",
"http://www.foodnetwork.com/recipes/sunny-anderson/radish-salad-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/cheese-stuffed-dates-with-prosciutto-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/roast-chicken-with-grapes-recipe.html",
"http://www.foodnetwork.com/recipes/roasted-sausages-and-grapes-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/sweet-roasted-grapes-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/salami-and-gorgonzola-biscuits-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/eggs-in-purgatory-with-salami-recipe.html",
"http://www.foodnetwork.com/recipes/anne-burrell/sweet-potato-casserole-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/nectarine-upside-down-cake-with-salted-caramel.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/blueberry-and-nectarine-cobbler-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/spicy-quinoa-with-sweet-potatoes.html",
"http://www.foodnetwork.com/recipes/rachael-ray/thai-cucumber-and-radish-salad-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/nectarine-tomato-salad-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/spiced-rice-with-nectarines-recipe.html",
"http://www.foodnetwork.com/recipes/emeril-lagasse/brandied-duck-liver-mousse-with-creole-mustard-sauce-recipe.html",
"http://www.foodnetwork.com/recipes/marcela-valladolid/grilled-stuffed-jalapeno-chiles-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/watermelon-and-cantaloupe-salad-with-mint-vinaigrette-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/watermelon-and-cantaloupe-salad-with-mint-and-basil-vinaigrette-recipe.html",
"http://www.foodnetwork.com/recipes/robin-miller/wilted-bok-choy-with-soy-sauce-and-cashews-recipe.html",
"http://www.foodnetwork.com/recipes/jamie-oliver/stir-fried-chinese-greens-with-ginger-oyster-and-soy-sauce-recipe.html",
"http://www.foodnetwork.com/recipes/grilled-shrimp-scampi-style-with-soy-sauce-fresh-ginger-and-garlic-recipe.html",
"http://www.foodnetwork.com/recipes/jamie-oliver/beef-with-soy-sauce-and-ginger-recipe.html",
"http://www.foodnetwork.com/recipes/rachael-ray/heck-of-a-jicama-salad-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/jicama-orange-salad-recipe.html",
"http://www.foodnetwork.com/recipes/anne-burrell/garnet-yam-bacon-and-apple-hash-recipe.html",
"http://www.foodnetwork.com/recipes/rachael-ray/cucumber-and-tomato-salad-recipe.html",
"http://www.foodnetwork.com/recipes/emeril-lagasse/vietnamese-summer-rolls-with-hot-mustard-sauce-recipe.html",
"http://www.foodnetwork.com/recipes/veggie-sandwich-with-pesto-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/israeli-couscous-salad-with-smoked-paprika-recipe.html",
"http://www.foodnetwork.com/recipes/patrick-and-gina-neely/black-eyed-peas-with-bacon-and-pork-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/lima-bean-dip-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/israeli-couscous-with-apples-cranberries-and-herbs-recipe.html",
"http://www.foodnetwork.com/recipes/melissa-darabian/israeli-couscous-tabouli-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/curried-couscous-salad-recipe.html",
"http://www.foodnetwork.com/recipes/patrick-and-gina-neely/black-eyed-pea-salad-recipe.html",
"http://www.foodnetwork.com/recipes/emeril-lagasse/alains-broiled-catfish-with-lima-beans-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/lemon-salmon-with-lima-beans-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/garbanzo-bean-and-olive-tapenade-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/garbanzo-bean-and-zucchini-salad-recipe.html",
"http://www.foodnetwork.com/recipes/artichoke-and-tuna-panini-with-garbanzo-bean-spread-recipe.html",
"http://www.foodnetwork.com/recipes/chicken-with-paprika-kidney-beans-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/israeli-couscous-and-tuna-salad-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/spinach-salad-with-orange-vinaigrette-recipe.html",
"http://www.foodnetwork.com/recipes/ellie-krieger/chinese-chicken-salad-recipe.html",
"http://www.foodnetwork.com/recipes/emeril-lagasse/garbanzo-beans-and-spinach-casserole-recipe.html",
"http://www.foodnetwork.com/recipes/ree-drummond/perfect-spinach-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/corn-and-avocado-salad.html",
"http://www.foodnetwork.com/recipes/sunny-anderson/mango-and-avocado-salad-recipe.html",
"http://www.foodnetwork.com/recipes/rachael-ray/tomato-onion-and-cucumber-salad-recipe.html",
"http://www.foodnetwork.com/recipes/tyler-florence/salad-nicoise-with-seared-tuna-recipe.html",
"http://www.foodnetwork.com/recipes/ellie-krieger/wheat-berry-salad-recipe2.html",
"http://www.foodnetwork.com/recipes/ina-garten/vinaigrette-for-green-salad-recipe.html",
"http://www.foodnetwork.com/recipes/alton-brown/fresh-broccoli-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/tomato-feta-pasta-salad-recipe.html",
"http://www.foodnetwork.com/recipes/aarti-sequeira/massaged-kale-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/balsamic-roasted-beet-salad-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/tuscan-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/fresh-corn-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ree-drummond/quick-italian-salad.html",
"http://www.foodnetwork.com/recipes/jeff-mauro/spring-pasta-salad-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/whipped-ricotta-salad.html",
"http://www.foodnetwork.com/recipes/alton-brown/spinach-salad-with-warm-bacon-dressing-recipe.html",
"http://www.foodnetwork.com/recipes/alton-brown/fruit-salad-with-vanilla-dressing-recipe.html",
"http://www.foodnetwork.com/recipes/alton-brown/parsley-salad-recipe.html",
"http://www.foodnetwork.com/recipes/paula-deen/red-potato-salad-recipe.html",
"http://www.foodnetwork.com/recipes/alexandra-guarnaschelli/chilled-asparagus-salad-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/citrus-salad-recipe.html",
"http://www.foodnetwork.com/recipes/patrick-and-gina-neely/watermelon-salad-recipe.html",
"http://www.foodnetwork.com/recipes/trisha-yearwood/broccoli-salad-recipe.html",
"http://www.foodnetwork.com/recipes/paula-deen/salmon-salad-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/antipasto-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/potato-salad-recipe.html",
"http://www.foodnetwork.com/recipes/rachael-ray/black-bean-and-corn-salad-recipe.html",
"http://www.foodnetwork.com/recipes/rachael-ray/greek-salad-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/orzo-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ree-drummond/layered-salad.html",
"http://www.foodnetwork.com/recipes/jamie-deen/broccoli-salad-recipe.html",
"http://www.foodnetwork.com/recipes/tyler-florence/fall-salad-recipe.html",
"http://www.foodnetwork.com/recipes/sandra-lee/quinoa-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/guacamole-salad-recipe.html",
 "http://www.foodnetwork.com/recipes/giada-de-laurentiis/grilled-vegetables-recipe.html"  ,  
 "http://www.foodnetwork.com/recipes/alton-brown/garden-vegetable-soup-recipe.html" ,
  "http://www.foodnetwork.com/recipes/giada-de-laurentiis/frittata-with-asparagus-tomato-and-fontina-recipe.html" , 
  "http://www.foodnetwork.com/recipes/bobby-flay/buckwheat-noodle-salad-recipe.html" ,
   "http://www.foodnetwork.com/recipes/food-network-kitchens/tofu-tacos-recipe.html" , 
   "http://www.foodnetwork.com/recipes/robin-miller/vegetarian-paella-recipe.html" , 
    "http://www.foodnetwork.com/recipes/alton-brown/vegetarian-steamed-dumplings-recipe.html" , 
     "http://www.foodnetwork.com/recipes/vegetarian-southern-style-collard-greens-recipe.html" , 
     "http://www.foodnetwork.com/recipes/food-network-kitchens/vegetable-biryani-recipe.html" , 
      "http://www.foodnetwork.com/recipes/food-network-kitchens/roasted-root-vegetables-recipe.html" , 
      "http://www.foodnetwork.com/recipes/ellie-krieger/grilled-vegetable-salad-with-feta-and-mint-recipe.html" , 
      "http://www.foodnetwork.com/recipes/alton-brown/vegetable-curry-recipe.html" , 
       "http://www.foodnetwork.com/recipes/rachael-ray/three-vegetable-penne-with-tarragon-basil-pesto-recipe.html" , 
       "http://www.foodnetwork.com/recipes/food-network-kitchens/vegetarian-ribollita-recipe.html" , 
        "http://www.foodnetwork.com/recipes/rachael-ray/roasted-squash-vegetable-medley-recipe.html" , 
        "http://www.foodnetwork.com/recipes/food-network-kitchens/seven-vegetable-couscous-recipe.html" , 
        "http://www.foodnetwork.com/recipes/moroccan-vegetables-with-couscous-recipe.html" ,
         "http://www.foodnetwork.com/recipes/vegetable-lasagna.html" ,
          "http://www.foodnetwork.com/recipes/vegetable-tofu-stir-fry-recipe.html" , 
          "http://www.foodnetwork.com/recipes/emeril-lagasse/creole-vegetable-jambalaya-recipe.html", 
          "http://www.foodnetwork.com/recipes/food-network-kitchens/shrimp-and-kale-pitas.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/skillet-orzo-with-tuna.html",
          "http://www.foodnetwork.com/recipes/rachael-ray/parmesan-crusted-chicken-breasts-with-tomato-and-basil-and-potatoes-with-peppers-and-onions-recipe.html",
          "http://www.foodnetwork.com/recipes/tyler-florence/chicken-stir-fry-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/gnocchi-with-bacon-and-escarole.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/turkey-sausage-tacos.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/glazed-salmon-with-spiced-carrots-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/white-clam-pizza-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/almost-famous-chicken-lettuce-wraps-recipe.html",
          "http://www.foodnetwork.com/recipes/guy-fieri/kobe-sliders-recipe.html",
          "http://www.foodnetwork.com/recipes/rachael-ray/buffalo-chicken-salad-recipe.html",
          "http://www.foodnetwork.com/recipes/guy-fieri/grilled-chicken-tortilla-soup-with-tequila-crema-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/chinese-beef-with-broccoli-recipe.html",
          "http://www.foodnetwork.com/recipes/guy-fieri/chicken-avocado-egg-rolls-recipe.html",
          "http://www.foodnetwork.com/recipes/tyler-florence/chicken-parmesan-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/general-tsos-chicken-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/spanish-style-noodles-with-chicken-and-sausage-recipe.html",
          "http://www.foodnetwork.com/recipes/rachael-ray/sausage-kale-and-lentil-soup-recipe.html",
          "http://www.foodnetwork.com/recipes/tyler-florence/beef-stroganoff-with-buttered-noodles-recipe.html",
          "http://www.foodnetwork.com/recipes/giada-de-laurentiis/chicken-carbonara-recipe.html",
          "http://www.foodnetwork.com/recipes/ree-drummond/pan-fried-pork-chops-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/beef-stroganoff-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/spaghetti-carbonara-recipe.html",
          "http://www.foodnetwork.com/recipes/ree-drummond/chicken-fried-steak-with-gravy-recipe.html",
          "http://www.foodnetwork.com/recipes/bobby-flay/shrimp-and-grits-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/patty-melts-recipe.html",
          "http://www.foodnetwork.com/recipes/claire-robinson/beef-stroganoff-recipe.html",
          "http://www.foodnetwork.com/recipes/amy-thielen/peppered-pork-and-parmesan-flatbread-sandwiches.html",
          "http://www.foodnetwork.com/recipes/amy-thielen/oven-baked-short-ribs-with-porter-beer-mop.html",
          "http://www.foodnetwork.com/recipes/amy-thielen/roast-chicken-with-green-herb-stuffing.html",
          'http://www.foodnetwork.com/recipes/food-network-kitchens/green-smoothie.html',
'http://www.foodnetwork.com/recipes/food-network-kitchens/red-berry-and-beet-smoothie.html',
'http://www.foodnetwork.com/recipes/food-network-kitchens/carrot-pineapple-smoothie.html',
'http://www.foodnetwork.com/recipes/food-network-kitchens/mango-coconut-and-chia-smoothie.html',
'http://www.foodnetwork.com/recipes/food-network-kitchens/peachy-oat-smoothie.html',
'http://www.foodnetwork.com/recipes/food-network-kitchens/blueberry-almond-smoothie.html',
'http://www.foodnetwork.com/recipes/food-network-kitchens/watermelon-and-cucumber-smoothie.html',
'http://www.foodnetwork.com/recipes/food-network-kitchens/apple-nut-smoothie.html',
'http://www.foodnetwork.com/recipes/food-network-kitchens/pumpkin-ginger-smoothie.html',
'http://www.foodnetwork.com/recipes/food-network-kitchens/cran-sicle-smoothie.html',
'http://www.foodnetwork.com/recipes/food-network-kitchens/banana-nog-smoothie.html',
'http://www.foodnetwork.com/recipes/sandra-lee/honeydew-smoothie-recipe.html',
"http://www.foodnetwork.com/recipes/dave-lieberman/triple-berry-banana-yogurt-smoothie-recipe.html",
'http://www.foodnetwork.com/recipes/anne-burrell/mango-strawberry-and-pineapple-smoothie-recipe.html',
'http://www.foodnetwork.com/recipes/ina-garten/tropical-smoothie-recipe.html',
'http://www.foodnetwork.com/recipes/ina-garten/orange-banana-smoothie-recipe.html',
'http://www.foodnetwork.com/recipes/bobby-flay/papaya-banana-smoothie-recipe.html',
"http://www.foodnetwork.com/recipes/ellie-krieger/peanut-butter-split-smoothie-recipe.html",
'http://www.foodnetwork.com/recipes/giada-de-laurentiis/raspberry-vanilla-smoothie-recipe.html',
'http://www.foodnetwork.com/recipes/ellie-krieger/peach-pie-smoothie-recipe.html',
'http://www.foodnetwork.com/recipes/michael-chiarello/fresh-fruit-smoothie-recipe.html',
'http://www.foodnetwork.com/recipes/ina-garten/sunrise-smoothie-recipe.html',
'http://www.foodnetwork.com/recipes/jeff-mauro/power-smoothie.html',
"http://www.foodnetwork.com/recipes/ellie-krieger/blueberry-blast-smoothie-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/kale-juice.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/peanut-butter-chocolate-pie.html",
"http://www.foodnetwork.com/recipes/sunny-anderson/chocoholic-smoothie-with-peppermint-rim-recipe.html",
"http://www.foodnetwork.com/recipes/geoffrey-zakarian/katies-kale-smoothie.html",
"http://www.foodnetwork.com/recipes/bobby-flay/creamed-kale-with-caramelized-shallots-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/kale-and-apple-salad-recipe.html",
"http://www.foodnetwork.com/recipes/rachael-ray/smothered-mushrooms-and-kale-recipe.html",
"http://www.foodnetwork.com/recipes/melissa-darabian/kale-slaw-recipe.html",
"http://www.foodnetwork.com/recipes/sandra-lee/peach-mango-smoothie-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/chocolate-peanut-butter-pudding-pie-recipe.html",
"http://www.foodnetwork.com/recipes/alton-brown/buff-smoothie-recipe.html",
"http://www.foodnetwork.com/recipes/melissa-darabian/chocolate-and-banana-smoothie-recipe.html",
"http://www.foodnetwork.com/recipes/guy-fieri/guys-rockin-smoothie-recipe.html",
"http://www.foodnetwork.com/recipes/peanut-butter-banana-shake-recipe.html",
"http://www.foodnetwork.com/recipes/nigella-lawson/go-get-em-smoothie-recipe.html",
"http://www.foodnetwork.com/recipes/paula-deen/vanilla-milkshake-recipe.html",
'http://www.foodnetwork.com/recipes/melissa-darabian/green-morning-smoothie-recipe.html',
'http://www.foodnetwork.com/recipes/ina-garten/banana-raspberry-smoothies-recipe.html',
"http://www.foodnetwork.com/recipes/cinnamon-roll-milkshake-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/homemade-chai-latte-recipe.html",
"http://www.foodnetwork.com/recipes/robin-miller/chai-tea-smoothies-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/frozen-fruit-smoothies-recipe.html",
"http://www.foodnetwork.com/recipes/emeril-lagasse/fresh-strawberry-milkshakes-recipe.html",
'http://www.foodnetwork.com/recipes/paula-deen/pina-colada-smoothie-recipe.html']

def remove_duplicates(values):
    output = []
    seen = set()
    for value in values:
        # If value has not been encountered yet,
        # ... add it to both list and set.
        if value not in seen:
            output.append(value)
            seen.add(value)
        else:
          print value
    return output

if __name__ == '__main__':
  result = remove_duplicates(recipe_database)
