recipe_database = ["http://www.foodnetwork.com/recipes/emeril-lagasse/vegetarian-chili-recipe.html"  , 
"http://www.foodnetwork.com/recipes/paula-deen/broccoli-salad-recipe.html",
"http://www.foodnetwork.com/recipes/trisha-yearwood/strawberry-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ellie-krieger/cucumber-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/shrimp-salad-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/mediterranean-salad-recipe.html",
"http://www.foodnetwork.com/recipes/guy-fieri/jicama-slaw-recipe.html",
"http://www.foodnetwork.com/recipes/paula-deen/southern-cornbread-salad-recipe.html",
"http://www.foodnetwork.com/recipes/emeril-lagasse/rock-shrimp-quesadillas-with-cantaloupe-berry-and-peach-salsa-recipe.html",
"http://www.foodnetwork.com/recipes/jicama-salad-recipe0.html",
"http://www.foodnetwork.com/recipes/chicken-paillard-with-tri-olive-tapanade-roast-sage-yams-and-sauteed-garlic-spinach-recipe.html",
"http://www.foodnetwork.com/recipes/lima-bean-soup-with-parmesan-bacon-crisp-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/broccoli-with-garlic-and-soy-sauce-recipe3.html",
"http://www.foodnetwork.com/recipes/cantaloupe-salad-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/watermelon-and-cantaloupe-salad-with-mint-vinaigrette-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/watermelon-and-cantaloupe-salad-with-mint-and-basil-vinaigrette-recipe.html",
"http://www.foodnetwork.com/recipes/robin-miller/wilted-bok-choy-with-soy-sauce-and-cashews-recipe.html",
"http://www.foodnetwork.com/recipes/jamie-oliver/stir-fried-chinese-greens-with-ginger-oyster-and-soy-sauce-recipe.html",
"http://www.foodnetwork.com/recipes/grilled-shrimp-scampi-style-with-soy-sauce-fresh-ginger-and-garlic-recipe.html",
"http://www.foodnetwork.com/recipes/jamie-oliver/beef-with-soy-sauce-and-ginger-recipe.html",
"http://www.foodnetwork.com/recipes/rachael-ray/heck-of-a-jicama-salad-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/jicama-orange-salad-recipe.html",
"http://www.foodnetwork.com/recipes/anne-burrell/garnet-yam-bacon-and-apple-hash-recipe.html",
"http://www.foodnetwork.com/recipes/rachael-ray/cucumber-and-tomato-salad-recipe.html",
"http://www.foodnetwork.com/recipes/emeril-lagasse/vietnamese-summer-rolls-with-hot-mustard-sauce-recipe.html",
"http://www.foodnetwork.com/recipes/veggie-sandwich-with-pesto-recipe.html",
"http://www.foodnetwork.com/recipes/patrick-and-gina-neely/black-eyed-peas-with-bacon-and-pork-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/lima-bean-dip-recipe.html",
"http://www.foodnetwork.com/recipes/patrick-and-gina-neely/black-eyed-pea-salad-recipe.html",
"http://www.foodnetwork.com/recipes/emeril-lagasse/alains-broiled-catfish-with-lima-beans-recipe.html",
"http://www.foodnetwork.com/recipes/food-network-kitchens/lemon-salmon-with-lima-beans-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/garbanzo-bean-and-olive-tapenade-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/garbanzo-bean-and-zucchini-salad-recipe.html",
"http://www.foodnetwork.com/recipes/artichoke-and-tuna-panini-with-garbanzo-bean-spread-recipe.html",
"http://www.foodnetwork.com/recipes/chicken-with-paprika-kidney-beans-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/israeli-couscous-and-tuna-salad-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/spinach-salad-with-orange-vinaigrette-recipe.html",
"http://www.foodnetwork.com/recipes/ellie-krieger/chinese-chicken-salad-recipe.html",
"http://www.foodnetwork.com/recipes/emeril-lagasse/garbanzo-beans-and-spinach-casserole-recipe.html",
"http://www.foodnetwork.com/recipes/ree-drummond/perfect-spinach-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/corn-and-avocado-salad.html",
"http://www.foodnetwork.com/recipes/sunny-anderson/mango-and-avocado-salad-recipe.html",
"http://www.foodnetwork.com/recipes/rachael-ray/tomato-onion-and-cucumber-salad-recipe.html",
"http://www.foodnetwork.com/recipes/tyler-florence/salad-nicoise-with-seared-tuna-recipe.html",
"http://www.foodnetwork.com/recipes/ellie-krieger/wheat-berry-salad-recipe2.html",
"http://www.foodnetwork.com/recipes/ina-garten/vinaigrette-for-green-salad-recipe.html",
"http://www.foodnetwork.com/recipes/alton-brown/fresh-broccoli-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/tomato-feta-pasta-salad-recipe.html",
"http://www.foodnetwork.com/recipes/aarti-sequeira/massaged-kale-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/balsamic-roasted-beet-salad-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/tuscan-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/fresh-corn-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ree-drummond/quick-italian-salad.html",
"http://www.foodnetwork.com/recipes/jeff-mauro/spring-pasta-salad-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/whipped-ricotta-salad.html",
"http://www.foodnetwork.com/recipes/alton-brown/spinach-salad-with-warm-bacon-dressing-recipe.html",
"http://www.foodnetwork.com/recipes/alton-brown/fruit-salad-with-vanilla-dressing-recipe.html",
"http://www.foodnetwork.com/recipes/alton-brown/parsley-salad-recipe.html",
"http://www.foodnetwork.com/recipes/paula-deen/red-potato-salad-recipe.html",
"http://www.foodnetwork.com/recipes/alexandra-guarnaschelli/chilled-asparagus-salad-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/citrus-salad-recipe.html",
"http://www.foodnetwork.com/recipes/patrick-and-gina-neely/watermelon-salad-recipe.html",
"http://www.foodnetwork.com/recipes/trisha-yearwood/broccoli-salad-recipe.html",
"http://www.foodnetwork.com/recipes/paula-deen/salmon-salad-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/antipasto-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/potato-salad-recipe.html",
"http://www.foodnetwork.com/recipes/rachael-ray/black-bean-and-corn-salad-recipe.html",
"http://www.foodnetwork.com/recipes/rachael-ray/greek-salad-recipe.html",
"http://www.foodnetwork.com/recipes/giada-de-laurentiis/orzo-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ree-drummond/layered-salad.html",
"http://www.foodnetwork.com/recipes/jamie-deen/broccoli-salad-recipe.html",
"http://www.foodnetwork.com/recipes/tyler-florence/fall-salad-recipe.html",
"http://www.foodnetwork.com/recipes/sandra-lee/quinoa-salad-recipe.html",
"http://www.foodnetwork.com/recipes/ina-garten/guacamole-salad-recipe.html",
 "http://www.foodnetwork.com/recipes/giada-de-laurentiis/grilled-vegetables-recipe.html"  ,  
 "http://www.foodnetwork.com/recipes/alton-brown/garden-vegetable-soup-recipe.html" ,
  "http://www.foodnetwork.com/recipes/giada-de-laurentiis/frittata-with-asparagus-tomato-and-fontina-recipe.html" , 
  "http://www.foodnetwork.com/recipes/bobby-flay/buckwheat-noodle-salad-recipe.html" ,
   "http://www.foodnetwork.com/recipes/food-network-kitchens/tofu-tacos-recipe.html" , 
   "http://www.foodnetwork.com/recipes/robin-miller/vegetarian-paella-recipe.html" , 
    "http://www.foodnetwork.com/recipes/alton-brown/vegetarian-steamed-dumplings-recipe.html" , 
     "http://www.foodnetwork.com/recipes/vegetarian-southern-style-collard-greens-recipe.html" , 
     "http://www.foodnetwork.com/recipes/food-network-kitchens/vegetable-biryani-recipe.html" , 
      "http://www.foodnetwork.com/recipes/food-network-kitchens/roasted-root-vegetables-recipe.html" , 
      "http://www.foodnetwork.com/recipes/ellie-krieger/grilled-vegetable-salad-with-feta-and-mint-recipe.html" , 
      "http://www.foodnetwork.com/recipes/alton-brown/vegetable-curry-recipe.html" , 
       "http://www.foodnetwork.com/recipes/rachael-ray/three-vegetable-penne-with-tarragon-basil-pesto-recipe.html" , 
       "http://www.foodnetwork.com/recipes/food-network-kitchens/vegetarian-ribollita-recipe.html" , 
        "http://www.foodnetwork.com/recipes/rachael-ray/roasted-squash-vegetable-medley-recipe.html" , 
        "http://www.foodnetwork.com/recipes/food-network-kitchens/seven-vegetable-couscous-recipe.html" , 
        "http://www.foodnetwork.com/recipes/moroccan-vegetables-with-couscous-recipe.html" ,
         "http://www.foodnetwork.com/recipes/vegetable-lasagna.html" ,
          "http://www.foodnetwork.com/recipes/vegetable-tofu-stir-fry-recipe.html" , 
          "http://www.foodnetwork.com/recipes/emeril-lagasse/creole-vegetable-jambalaya-recipe.html", 
          "http://www.foodnetwork.com/recipes/food-network-kitchens/shrimp-and-kale-pitas.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/skillet-orzo-with-tuna.html",
          "http://www.foodnetwork.com/recipes/rachael-ray/parmesan-crusted-chicken-breasts-with-tomato-and-basil-and-potatoes-with-peppers-and-onions-recipe.html",
          "http://www.foodnetwork.com/recipes/tyler-florence/chicken-stir-fry-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/gnocchi-with-bacon-and-escarole.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/turkey-sausage-tacos.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/glazed-salmon-with-spiced-carrots-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/white-clam-pizza-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/almost-famous-chicken-lettuce-wraps-recipe.html",
          "http://www.foodnetwork.com/recipes/guy-fieri/kobe-sliders-recipe.html",
          "http://www.foodnetwork.com/recipes/rachael-ray/buffalo-chicken-salad-recipe.html",
          "http://www.foodnetwork.com/recipes/guy-fieri/grilled-chicken-tortilla-soup-with-tequila-crema-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/chinese-beef-with-broccoli-recipe.html",
          "http://www.foodnetwork.com/recipes/guy-fieri/chicken-avocado-egg-rolls-recipe.html",
          "http://www.foodnetwork.com/recipes/tyler-florence/chicken-parmesan-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/general-tsos-chicken-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/spanish-style-noodles-with-chicken-and-sausage-recipe.html",
          "http://www.foodnetwork.com/recipes/rachael-ray/sausage-kale-and-lentil-soup-recipe.html",
          "http://www.foodnetwork.com/recipes/tyler-florence/beef-stroganoff-with-buttered-noodles-recipe.html",
          "http://www.foodnetwork.com/recipes/giada-de-laurentiis/chicken-carbonara-recipe.html",
          "http://www.foodnetwork.com/recipes/ree-drummond/pan-fried-pork-chops-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/beef-stroganoff-recipe.html",
          "http://www.foodnetwork.com/recipes/food-network-kitchens/spaghetti-carbonara-recipe.html",
          "http://www.foodnetwork.com/recipes/ree-drummond/chicken-fried-steak-with-gravy-recipe.html",
          "http://www.foodnetwork.com/recipes/bobby-flay/shrimp-and-grits-recipe.html","http://www.foodnetwork.com/recipes/food-network-kitchens/patty-melts-recipe.html","http://www.foodnetwork.com/recipes/claire-robinson/beef-stroganoff-recipe.html","http://www.foodnetwork.com/recipes/amy-thielen/peppered-pork-and-parmesan-flatbread-sandwiches.html","http://www.foodnetwork.com/recipes/amy-thielen/oven-baked-short-ribs-with-porter-beer-mop.html","http://www.foodnetwork.com/recipes/amy-thielen/roast-chicken-with-green-herb-stuffing.html"]
