beans = ['garbanzo beans', 'kidney beans', 'lima beans', 'black eye peas', 'soy beans']
fruit = ['apple', 'pinapple', 'strawberries', 'pomegranate seeds', 'pear', 'cranberries', 'coconut', 'dates', 'orange', 'rasins', 'watermelon balls', 'cantaloupe balls', 'honeydew balls', 'grapes', 'kiwi', 'lemon wedges']
nuts = ['almonds', 'sunflower seeds', 'walnuts', 'sesame seeds', 'cashews', 'pine nuts', 'peanuts', 'pecans']
vegtables = ['cabbage', 'tomatoes', 'water cress', 'beets', 'pickled beets', 'eggplant', 'yam', 'zucchini', 'cherry tomatoes', 'spaghetti squash', 'sweet peas', 'sweet potato', 'radishes', 'snow peas', 'peppers', 'pickled onions', 'jimica', 'onions', 'olives', 'jalapenos', 'mushrooms', 'cauliflower', 'celery', 'cucumber', 'alfalfa sprouts', 'asparagus', 'avocado', 'beets', 'broccoli', 'bean sprouts', 'brussel sprouts', 'corn', 'baby corn', 'carrots']
meat = ['bacon bits', 'tofu', 'beef', 'tuna', 'fish', 'steak', 'ham', 'chicken', 'turkey', 'shrimp', 'crab meat', 'salami', 'ham']
dairy = ['jack', 'goat cheese', 'gorgonzola', 'parmesan', 'mozzarella', 'cheddar', 'feta cheese', 'blue cheese', 'provolone', 'cottage cheese', 'hard boiled egg']
herbs = ['cilantro', 'flowers', 'garlic', 'basil', 'mint', 'ginger', 'pepper', 'salt']
carbs = ['fritos', 'crispy noodles', 'tortilla strips', 'croutons', 'bread','couscous']
salad_ingredients = beans + fruit + nuts + vegtables + meat + dariy + herbs + carbs